name: Backend Linting

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/lint-backend.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/lint-backend.yml'
  workflow_dispatch:

jobs:
  lint-backend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.11'
        enable-cache: true
        
    - name: Install Python dependencies
      run: |
        cd backend
        uv sync --dev
        
    - name: Run Ruff linting
      run: |
        cd backend
        uv run ruff check . --output-format=github
      continue-on-error: true
      
    - name: Run Ruff formatting check
      run: |
        cd backend
        uv run ruff format --check .
      continue-on-error: true
      
    - name: Run mypy type checking
      run: |
        cd backend
        uv run mypy .
      continue-on-error: true
      
    - name: Generate linting summary
      if: always()
      run: |
        echo "## Backend Linting Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Ruff Linting" >> $GITHUB_STEP_SUMMARY
        echo "- Status: ${{ steps.ruff-lint.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Ruff Formatting" >> $GITHUB_STEP_SUMMARY
        echo "- Status: ${{ steps.ruff-format.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### mypy Type Checking" >> $GITHUB_STEP_SUMMARY
        echo "- Status: ${{ steps.mypy.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Note:** Linting failures are non-blocking and serve as warnings only." >> $GITHUB_STEP_SUMMARY
